name: Tailwindcss

on:
  workflow_run:
    workflows: [Black Formatter]
    types:
      - completed

jobs:
  tailwindcss:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tailwindcss
        run: |
          sudo apt install -y npm
          npm ci
          cd internal/static
          npx tailwindcss -i src/style.css -o css/main.css

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update tailwindcss
